expose intercom JS API 'showArticle' function through useIntercom
devrnt/react-use-intercom pull request #405
Opened 2022-01-28 14:51 UTC by Jonneitapuro

The Intercom Javascript API now supports opening an article in the Messenger widget (see: https://developers.intercom.com/installing-intercom/docs/intercom-javascript#intercomshowarticle-articleid)

This PR exposes that API through the useIntercom hook.

2022-01-28 17:17 UTC, devrnt commented
Thanks, this is great!

2022-01-28 17:23 UTC, devrnt requested changes
Looks great! Would you mind updating the `README` as well?

2022-01-28 17:23 UTC, devrnt commented on playground/modules/useIntercom/useIntercom.tsx
> +    showArticle(123);
I've created a test article in Intercom, you can replace the id with `4013997`

2022-01-28 17:23 UTC, devrnt commented on playground/modules/useIntercom/useIntercom.tsx
> +        <Button label="Track event with metadata" onClick={handleShowArticle} />
Update the button label

2022-01-28 17:23 UTC, devrnt commented on src/types.ts
> +   * Opens the messenger with the specified article open
```suggestion
   * Opens the messenger with the specified article
```

2022-01-28 19:43 UTC, Jonneitapuro commented
I'll do the fixes tomorrow :)

2022-01-29 09:29 UTC, Jonneitapuro commented
@devrnt I pushed my fixes to the requested changes. If I still missed something let me know :)

2022-01-29 11:27 UTC, devrnt approved these changes

2022-01-29 11:28 UTC, devrnt commented
Thanks again, looks great!

2022-01-29 11:29 UTC, merged

2022-01-29 11:38 UTC, devrnt commented
[v1.5.0](https://github.com/devrnt/react-use-intercom/releases/tag/v1.5.0)